inferenceExtension:
  replicas: 1
  image:
    name: epp-ig-latencypredictor-merged-2
    hub: us-docker.pkg.dev/kaushikmitra-gke-dev/kaushikmitra-docker-repo
    tag: latest
    pullPolicy: Always
  extProcPort: 9002
  env: []
  pluginsConfigFile: "custom-plugins.yaml"
  # Define additional container ports
  extraContainerPorts: []
  # Define additional service ports
  extraServicePorts: []
#  extraServicePorts:
#    - name: http
#      port: 8081
#      protocol: TCP
#      targetPort: 8081

  # This is the plugins configuration file.
  pluginsCustomConfig:
    custom-plugins.yaml: |
      apiVersion: inference.networking.x-k8s.io/v1alpha1
      kind: EndpointPickerConfig
      featureGates:
      - dataLayer
      - prepareDataPlugins
      plugins:
      - type: queue-scorer
      - type: kv-cache-utilization-scorer
      - type: prefix-cache-scorer
      - type: predicted-latency-scorer
        parameters:
          samplingMean: 1000.0
          maxSampledTokens: 0
          sloBufferFactor: 1.0
          negHeadroomTTFTWeight: 0.8
          negHeadroomTPOTWeight: 0.2
          headroomTTFTWeight: 0.8
          headroomTPOTWeight: 0.2
          headroomSelectionStrategy: "least"
          compositeKVWeight: 1.0
          compositeQueueWeight: 1.0
          compositePrefixWeight: 1.0
          epsilonExploreSticky: 0.01
          epsilonExploreNeg: 0.01
          affinityGateTau: 0.80
          affinityGateTauGlobal: 0.99
          selectionMode: "linear"
      - name: metrics-data-source
        type: metrics-data-source
      - name: model-server-protocol-metrics
        type: model-server-protocol-metrics
        parameters:
          defaultEngine: "vllm"
          engineConfigs:
          - name: vllm
            queuedRequestsSpec: "vllm:num_requests_waiting"
            runningRequestsSpec: "vllm:num_requests_running"
            kvUsageSpec: "vllm:gpu_cache_usage_perc"
            loraSpec: "vllm:lora_requests_info"
            cacheInfoSpec: "vllm:cache_config_info"
      data:
        sources:
        - pluginRef: metrics-data-source
          extractors:
          - pluginRef: model-server-protocol-metrics
      schedulingProfiles:
      - name: default
        plugins:
        - pluginRef: predicted-latency-scorer
          

  # Example environment variables:
  # env:
  #   ENABLE_EXPERIMENTAL_FEATURE: "true"

  flags:
    # Log verbosity
    v: 1

  affinity: {}

  tolerations: []

  resources:
   requests:
     cpu: 4000m
     memory: 8Gi
   limits:
#      cpu: 4000m
     memory: 16Gi

  # Sidecar configuration for EPP
  sidecar:
    enabled: false

  # Monitoring configuration for EPP
  monitoring:
    interval: "10s"
    # Prometheus ServiceMonitor will be created when enabled for EPP metrics collection
    prometheus:
      enabled: true
      auth:
        enabled: true
        # Service account token secret for authentication
        secretName: inference-gateway-sa-metrics-reader-secret
      # additional labels for the ServiceMonitor
      extraLabels: {}
  tracing:
    enabled: false
    otelExporterEndpoint: "http://localhost:4317"
    sampling:
      sampler: "parentbased_traceidratio"
      samplerArg: "0.1"

  # Latency Predictor Configuration
  latencyPredictor:
    # common latencyPredictor setting exists in config/charts/inference-extension/values.yaml
    enabled: true

inferencePool:
  targetPorts:
    - number: 8000
  modelServerType: vllm # vllm, triton-tensorrt-llm
  apiVersion: inference.networking.k8s.io/v1
  # modelServers: # REQUIRED
  #   matchLabels:
  #     app: vllm-qwen3-32b

  # Should only used if apiVersion is inference.networking.x-k8s.io/v1alpha2,
  # This will soon be deprecated when upstream GW providers support v1, just doing something simple for now.
  targetPortNumber: 8000

# Options: ["gke", "istio", "none"]
provider:
  name: gke

  # GKE-specific configuration.
  # This block is only used if name is "gke".
  gke:
    # Set to true if the cluster is an Autopilot cluster.
    autopilot: false

  # Istio-specific configuration.
  # This block is only used if name is "istio".
  istio:
    destinationRule:
      # Provide a way to override the default calculated host
      host: ""
      # Optional: Enables customization of the traffic policy
      trafficPolicy: {}
        # connectionPool:
        #   http:
        #     maxRequestsPerConnection: 256000

# experimentalHttpRoute section is used to deploy httproute as part of the epp helm chart.
# this section is temporary and should be extracted to a separate chart.
experimentalHttpRoute:
  enabled: true # a flag to indicate whether to create the httproute as part of the chart or not.
  inferenceGatewayName: inference-gateway
