{{- define "inference-extension.service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-api-inference-extension.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-api-inference-extension.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway-api-inference-extension.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc-ext-proc
      protocol: TCP
      port: {{ .Values.inferenceExtension.extProcPort | default 9002 }}
    - name: http-metrics
      protocol: TCP
      port: {{ .Values.inferenceExtension.metricsPort | default 9090 }}
    {{- if and .Values.latencyPredictor .Values.latencyPredictor.enabled }}
    - name: training-port
      protocol: TCP
      port: {{ .Values.latencyPredictor.trainingServer.port | default 8000 }}
    {{- $startPort := .Values.latencyPredictor.predictionServers.startPort | default 8001 }}
    {{- range $i := until (.Values.latencyPredictor.predictionServers.count | default 2 | int) }}
    - name: predict-port-{{ add $i 1 }}
      protocol: TCP
      port: {{ add $startPort $i }}
    {{- end }}
    {{- end }}
    {{- with .Values.inferenceExtension.extraServicePorts }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
  type: ClusterIP
---
{{- end }}
